import { Command } from 'commander';
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';
import { isCommanderError } from '../utils/commander';
import { print, success, failure } from '../utils/output';

const ELEMENTS_TEMPLATE = {
  version: '1.0',
  description: 'Starter: create a minimal element set',
  changes: [
    {
      op: 'createElement',
      type: 'application-component',
      name: 'My Application',
      tempId: 'app-main',
    },
    {
      op: 'createElement',
      type: 'business-actor',
      name: 'Business User',
      tempId: 'actor-user',
    },
    {
      op: 'createRelationship',
      type: 'serving-relationship',
      sourceId: 'app-main',
      targetId: 'actor-user',
      tempId: 'rel-serves',
      name: 'Application serves user',
    },
  ],
};

const VIEW_TEMPLATE = {
  version: '1.0',
  description: 'Starter: create and populate a view',
  idFiles: ['01-elements.ids.json'],
  changes: [
    {
      op: 'createView',
      name: 'Application Overview',
      viewpoint: 'application_cooperation',
      tempId: 'view-overview',
    },
    {
      op: 'addToView',
      viewId: 'view-overview',
      elementId: 'app-main',
      x: 120,
      y: 120,
      width: 140,
      height: 55,
      tempId: 'vo-app-main',
    },
    {
      op: 'addToView',
      viewId: 'view-overview',
      elementId: 'actor-user',
      x: 420,
      y: 120,
      width: 140,
      height: 55,
      tempId: 'vo-actor-user',
    },
    {
      op: 'addConnectionToView',
      viewId: 'view-overview',
      relationshipId: 'rel-serves',
      sourceVisualId: 'vo-app-main',
      targetVisualId: 'vo-actor-user',
    },
  ],
};

const WORKFLOW_README = `# archicli Starter Workflow

This folder was generated by \`archicli init\`.

## Files

- \`01-elements.json\`: create starter elements and relationship
- \`02-view.json\`: create a view, add elements, add connection

## Apply/Poll Cycle

1. Verify server/model readiness:
\`archicli doctor\`
2. Validate templates:
\`archicli verify 01-elements.json --semantic\`
\`archicli verify 02-view.json --semantic\`
3. Apply and poll:
\`archicli batch apply 01-elements.json --poll\`
\`archicli batch apply 02-view.json --poll --layout\`

## Common Tasks

- Create element: edit \`01-elements.json\` and add a \`createElement\` op.
- Create view: edit \`02-view.json\` and add a \`createView\` op.
- Export view(s): \`archicli view export --all --dir exports\`.
- Poll an operation manually: \`archicli ops status <operationId> --poll\`.
`;

function ensureEmptyOrForced(dir: string, force: boolean): string | null {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
    return null;
  }
  const entries = readdirSync(dir);
  if (entries.length > 0 && !force) {
    return `Target directory is not empty: ${dir}. Use --force to overwrite existing files.`;
  }
  return null;
}

/**
 * Bootstrap a minimal BOM workflow in the current or target directory.
 */
export function initCommand(): Command {
  return new Command('init')
    .description(
      'Create starter BOM templates and a quick workflow README.\n\n' +
        'Designed for first-run onboarding in a new/empty working directory.'
    )
    .argument('[dir]', 'target directory (default: current working directory)')
    .option('--force', 'allow writing into a non-empty target directory')
    .action(async (dir: string | undefined, options: { force?: boolean }, cmd: Command) => {
      try {
        const targetDir = resolve(dir ?? process.cwd());
        const force = Boolean(options.force);

        const dirValidationError = ensureEmptyOrForced(targetDir, force);
        if (dirValidationError) {
          print(failure('INIT_DIR_NOT_EMPTY', dirValidationError));
          cmd.error('', { exitCode: 1 });
          return;
        }

        const files: Array<{ name: string; content: string }> = [
          { name: '01-elements.json', content: JSON.stringify(ELEMENTS_TEMPLATE, null, 2) + '\n' },
          { name: '02-view.json', content: JSON.stringify(VIEW_TEMPLATE, null, 2) + '\n' },
          { name: 'README.md', content: WORKFLOW_README },
        ];

        const createdFiles: string[] = [];
        for (const file of files) {
          const targetPath = join(targetDir, file.name);
          if (existsSync(targetPath) && !force) {
            print(
              failure(
                'INIT_FILE_EXISTS',
                `Refusing to overwrite existing file: ${targetPath}. Re-run with --force to overwrite.`
              )
            );
            cmd.error('', { exitCode: 1 });
            return;
          }
          writeFileSync(targetPath, file.content, 'utf-8');
          createdFiles.push(targetPath);
        }

        print(
          success({
            directory: targetDir,
            files: createdFiles,
            nextSteps: [
              `cd ${targetDir}`,
              'archicli doctor',
              'archicli batch apply 01-elements.json --poll',
              'archicli batch apply 02-view.json --poll --layout',
              'archicli view export --all --dir exports',
            ],
          })
        );
      } catch (err) {
        if (isCommanderError(err)) throw err;
        print(failure('INIT_FAILED', String(err)));
        cmd.error('', { exitCode: 1 });
      }
    });
}
